# docker-compose.yml
version: '3.3'

services:

  pyspark:
    image: jupyter-pyspark
    # limit the memory and cpu usage
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    container_name: pyspark
    ports:
      - "8888:8888"
    volumes:
      - ./working_dir:/home/andres/working_dir
    user: root
    working_dir: /home/andres/working_dir
    env_file:
      - ./working_dir/.env
    environment:
      JUPYTER_ENABLE_LAB: '1' 
      JUPYTER_TOKEN: 'andres'
      NB_USER: andres
      NB_GID: 1000
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: '-R'
      SPARK_CLASSPATH: '/home/andres/working_dir/driver_jdbc/postgresql-42.2.27.jre7.jar'
    networks:
      pyspark_network:
        ipv4_address: 172.7.7.1

networks:
  pyspark_network: # Name of the network
    ipam: # IP Address Management
      driver: default
      config:
        - subnet: 172.7.7.0/16 # Subnet
        # 172.7.7.0 is the default subnet for docker
        # 16 is the number of bits used for the network